#!/usr/bin/env bash
# configures Nginx server so that /redirect_me is redirecting to another page
# The redirection must be a “301 Moved Permanently”

sudo apt-get -y install nginx
sudo bash -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'

redirect="\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"

sudo sed -i "53s|.*|$redirect|" /etc/nginx/sites-enabled/default

sudo /etc/init.d/nginx restart
