#!/usr/bin/env bash
# Transfer a file via ssh from client to server

filepath="$1"
ipaddrs="$2"
username="$3"
sshkey_path="$4"

if [ "$#" -lt 3 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -o StrictHostKeyChecking=no -i "$sshkey_path" "$filepath" "$username"@"$ipaddrs":~/
fi
